# -*- coding: utf-8 -*-
"""gerar_graficos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VVh_SR_Y3_RYacBcKnDC5KiFwwvLMmpi
"""

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_excel("oddeven4.xlsx")

data.index = data.loc[:, "Tamanho do Problema"]
data = data.astype(float)
speedup = data.iloc[:,8:14]
eficiencia = data.iloc[:,14:]

speedup.columns = [2, 3, 4, 6, 8, 12]
speedup = speedup.transpose()
speedup

max_cores = 12
ax = speedup.plot()
plt.xlim(0, 14)
plt.ylim(0, 14)
plt.plot(range(15), range(15), label="Identidade", color='red', linestyle='--')
plt.legend(loc='best')
plt.xlabel(xlabel='Cores')
plt.ylabel(ylabel='Speedup')
plt.savefig("speedup_core.png")

eficiencia.columns = [2, 3, 4, 6, 8, 12]
eficiencia = eficiencia.transpose()
eficiencia

ax = eficiencia.plot()
plt.legend(loc='best')
plt.xlabel(xlabel='Cores')
plt.ylabel(ylabel='Eficiência')
plt.savefig("eficiencia_core.png")

eficiencia = eficiencia.transpose()
eficiencia.plot()
plt.legend(loc='best')
plt.xlabel(xlabel='Tamanho do Problema')
plt.ylabel(ylabel='Eficiência')
plt.savefig("eficiencia_problema.png")



